handle 403 error
sentinelsat/sentinelsat pull request #491
Opened 2021-06-01 14:22 UTC by z4zz

handle 403 error while Fetching archival status by `download all()`

Full error cause message for online product: 
> An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "_username_"

Full error cause message for offline product: 
> User '_username_' offline products retrieval quota exceeded (20 fetches max) trying to fetch product _PRODUCT_FILENAME_ (_BYTES_COUNT_ bytes compressed)

2021-06-01 18:38 UTC, valgur requested changes
Good catch, thanks!
We should also add a simple test case for it here https://github.com/sentinelsat/sentinelsat/blob/main/tests/test_download.py#L75-L97
Do you want to take a shot at it or I could also take care of it in a separate PR?

2021-06-01 18:38 UTC, valgur commented on sentinelsat/sentinel.py
>              self.logger.error(msg)
I would also include the full cause messages as code comments for context.
```suggestion
        elif r.status_code == 403 and cause and "concurrent flows" in cause:
            # cause: 'An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "username""'
            self.logger.debug("Product is online but concurrent downloads limit was exceeded")
            return False
        elif r.status_code == 403:
            # cause: 'User 'username' offline products retrieval quota exceeded (20 fetches max) trying to fetch product PRODUCT_FILENAME (BYTES_COUNT bytes compressed)'
            msg = f"User quota exceeded: {cause}"
            self.logger.error(msg)
```

2021-06-01 18:49 UTC, z4zz commented
I'm not familiar with tests, I'll leave that to you

2021-06-07 08:09 UTC, j08lue commented
> I'm not familiar with tests, I'll leave that to you

Maybe now is the time to get into it, @z4zz? 😉

2021-06-08 19:33 UTC, j08lue commented
@z4zz something went wrong with CI. How about you add a CHANGELOG entry for this fix, which should trigger it cleanly (and is nice to get, anyways)?

2021-06-08 21:17 UTC, j08lue commented
If you just add a line to CHANGELOG, it might go well from there. If not, we should raise another issue to fix the Autoblack/Pytest interplay.

2021-06-25 21:05 UTC, j08lue commented on tests/test_download.py
> +                "cause-message":'An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "mock_user"'}
```suggestion
                "cause-message":'An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "mock_user"'
```

2021-06-26 20:43 UTC, j08lue commented on CHANGELOG.rst
> +* Better handling 403 error in ``trigger_offline_retrieval()``
```suggestion
* Better handling 403 error in `trigger_offline_retrieval()` (`#491 <https://github.com/sentinelsat/sentinelsat/issues/491>`_ `@z4zz <https://github.com/z4zz>`_)
```

2021-07-02 19:02 UTC, j08lue commented
Great you added the test @z4zz. There was a syntax error blocking the CI, but that is fixed now. Now there is only a bit of test logic that needs fixing, it seems, before this PR can go through. @valgur, could you be persuaded to look into that?

2021-07-03 04:12 UTC, j08lue commented
Ok, never mind. I get what is happening: In some cases, the server includes a `cause-message` header when it returns an error code (in this case 403), and you use that to distinguish between different cases of 403. That header is what you added to the tests together with a new case, in order to distinguish between the cause being too many streams for an online product or too many fetch requests for an LTA product. What a mess this LTA has caused...

But nice catch, thanks @z4zz, we can merge this now.

2021-07-03 04:12 UTC, merged